/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Noores (https://sketchfab.com/nuks)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ai-robot-f7c4e4dcd1594e3e92b2d35a4ec8a93a
Title: AI Robot
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Head_Head_0: THREE.Mesh;
    Head_EyeBorder_0: THREE.Mesh;
    Head_Ears_0: THREE.Mesh;
    Head_Eyes_0: THREE.Mesh;
    Antenna_Antenna_0: THREE.Mesh;
    Antenna_Holder_0: THREE.Mesh;
    Antenna_light_0: THREE.Mesh;
    Chest_chestMat_0: THREE.Mesh;
    Hips_hipsMat_0: THREE.Mesh;
    Neck_Neck_0: THREE.Mesh;
    MidSpine_midSpineMat_0: THREE.Mesh;
    RightWheel_Wheelmat_0: THREE.Mesh;
    RightWheel_wheelHolderMAt_0: THREE.Mesh;
    LeftArm_HandCircleMat_0: THREE.Mesh;
    LeftArm_AfterCircleMat_0: THREE.Mesh;
    LeftArm_ForeArmMat_0: THREE.Mesh;
    LeftArm_FingersMAt_0: THREE.Mesh;
    LeftArm_HandMad_0: THREE.Mesh;
    LeftWheel_Wheelmat_0: THREE.Mesh;
    LeftWheel_wheelHolderMAt_0: THREE.Mesh;
    RightArm_HandCircleMat_0: THREE.Mesh;
    RightArm_AfterCircleMat_0: THREE.Mesh;
    RightArm_ForeArmMat_0: THREE.Mesh;
    RightArm_FingersMAt_0: THREE.Mesh;
    RightArm_HandMad_0: THREE.Mesh;
  };
  materials: {
    Head: THREE.MeshStandardMaterial;
    EyeBorder: THREE.MeshStandardMaterial;
    Ears: THREE.MeshPhysicalMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Antenna: THREE.MeshStandardMaterial;
    Holder: THREE.MeshStandardMaterial;
    light: THREE.MeshStandardMaterial;
    chestMat: THREE.MeshStandardMaterial;
    hipsMat: THREE.MeshStandardMaterial;
    Neck: THREE.MeshStandardMaterial;
    midSpineMat: THREE.MeshStandardMaterial;
    Wheelmat: THREE.MeshStandardMaterial;
    wheelHolderMAt: THREE.MeshStandardMaterial;
    HandCircleMat: THREE.MeshPhysicalMaterial;
    AfterCircleMat: THREE.MeshStandardMaterial;
    ForeArmMat: THREE.MeshStandardMaterial;
    FingersMAt: THREE.MeshStandardMaterial;
    HandMad: THREE.MeshStandardMaterial;
  };
};

export function RobotModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/ai_robot.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.24, 0.012]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head_Head_0.geometry}
          material={materials.Head}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head_EyeBorder_0.geometry}
          material={materials.EyeBorder}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head_Ears_0.geometry}
          material={materials.Ears}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head_Eyes_0.geometry}
          material={materials.Eyes}
        />
        <group position={[0, -0.001, 0.094]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antenna_Antenna_0.geometry}
            material={materials.Antenna}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antenna_Holder_0.geometry}
            material={materials.Holder}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antenna_light_0.geometry}
            material={materials.light}
          />
        </group>
      </group>
      <group position={[-0.049, 0.047, -0.003]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightWheel_Wheelmat_0.geometry}
          material={materials.Wheelmat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightWheel_wheelHolderMAt_0.geometry}
          material={materials.wheelHolderMAt}
        />
      </group>
      <group position={[-0.054, 0.145, -0.002]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftArm_HandCircleMat_0.geometry}
          material={materials.HandCircleMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftArm_AfterCircleMat_0.geometry}
          material={materials.AfterCircleMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftArm_ForeArmMat_0.geometry}
          material={materials.ForeArmMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftArm_FingersMAt_0.geometry}
          material={materials.FingersMAt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftArm_HandMad_0.geometry}
          material={materials.HandMad}
        />
      </group>
      <group position={[0.049, 0.047, -0.003]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftWheel_Wheelmat_0.geometry}
          material={materials.Wheelmat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LeftWheel_wheelHolderMAt_0.geometry}
          material={materials.wheelHolderMAt}
        />
      </group>
      <group position={[0.054, 0.145, -0.002]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightArm_HandCircleMat_0.geometry}
          material={materials.HandCircleMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightArm_AfterCircleMat_0.geometry}
          material={materials.AfterCircleMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightArm_ForeArmMat_0.geometry}
          material={materials.ForeArmMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightArm_FingersMAt_0.geometry}
          material={materials.FingersMAt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RightArm_HandMad_0.geometry}
          material={materials.HandMad}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chest_chestMat_0.geometry}
        material={materials.chestMat}
        position={[0, 0.135, 0.006]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hips_hipsMat_0.geometry}
        material={materials.hipsMat}
        position={[0, 0.065, 0.009]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Neck_Neck_0.geometry}
        material={materials.Neck}
        position={[0.001, 0.174, 0.006]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MidSpine_midSpineMat_0.geometry}
        material={materials.midSpineMat}
        position={[0, 0.096, 0.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.053}
      />
    </group>
  );
}

useGLTF.preload('/models/ai_robot.glb');
